Fix missing torch* nightlies by using latest stable
Use the latest stable version of torch* (torchaudio, torchdata,
torchvision and torchtune) to fix the build error:

ERROR: No matching distribution found for torchtune==0.6.0.dev20250115

We have to use `--no-deps` because the dev build of torch is
incompatible with the torch* packages.